# Generated by Django 3.2 on 2023-01-26 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='movie',
            name='place',
            field=models.CharField(blank=True, choices=[('In Theatre', 'In Theatre'), ('On your device', 'On your device')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
