# Generated by Django 3.2 on 2023-01-26 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_movie_cast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.cast_of_movie'),
        ),
    ]
