# Generated by Django 3.2 on 2023-01-26 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_movie_cast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='cast',
            new_name='movie_cast',
        ),
    ]
